version: "3.3"

services:
  db:
    container_name: 'site-name-wp-db'
    image: 'mysql:latest'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - '18766:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sitename_wp_db
      MYSQL_USER: bigboss
      MYSQL_PASSWORD: topsecret
  wordpress:
    container_name: 'sitename-wp'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: bigboss
      WORDPRESS_DB_PASSWORD: topsecret
      WORDPRESS_DB_NAME: sitename_wp_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"

